name: dictionary-app

services:
  db:
    container_name: postgres
    image: postgres:16.2
    restart: always
    ports:
      - 3002:5432
    networks:
      - dictionary
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d

  dbadmin:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 3003:8080
    networks:
      - dictionary
    depends_on:
      - db

  api:
    container_name: server
    build: ./server
    ports:
      - 3001:3001
    networks:
      - dictionary
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DB=${POSTGRES_DB}
    depends_on:
      - db

networks:
  dictionary:
    driver: bridge
